<script setup lang="ts">
import { computed, ref } from 'vue'
import { api } from './services/api'
import { connect } from './services/websocket'
const username = ref(''); const password = ref(''); const user = ref<any>(); const state = ref<any>(); const side = ref('BUY'); const symbol = ref('AAPL'); const price = ref(180); const quantity = ref(10); const message = ref('')
const openOrders = computed(() => state.value?.orders.filter((order: any) => order.status !== 'FILLED') ?? []); const filledOrders = computed(() => state.value?.orders.filter((order: any) => order.status === 'FILLED') ?? [])
async function refreshState() { state.value = await api(`/state?userId=${user.value.userId}`) }
async function auth(action: 'login' | 'register') { try { user.value = await api(`/auth/${action}`, { method: 'POST', body: JSON.stringify({ username: username.value, password: password.value }) }); await refreshState(); connect(user.value.userId, async event => { if (event.type === 'market:update') state.value.stocks = event.data; if (event.type === 'user:update' || event.type === 'trade:new') await refreshState() }) } catch (error) { message.value = (error as Error).message } }
async function submit() { try { await api('/orders', { method: 'POST', body: JSON.stringify({ userId: user.value.userId, symbol: symbol.value, side: side.value, price: Number(price.value), quantity: Number(quantity.value) }) }); await refreshState() } catch (error) { message.value = (error as Error).message } }
</script>
<template><main><h1>Stock Trading Simulator</h1><section v-if="!user"><input v-model="username" placeholder="用户名"><input v-model="password" type="password" placeholder="密码"><button @click="auth('login')">登录</button><button @click="auth('register')">注册</button></section><section v-else><p>用户：{{ state.user.username }}　资金：{{ state.user.cash.toFixed(2) }}</p><h2>行情</h2><table><tr><th>代码</th><th>名称</th><th>最新价</th><th>涨跌幅</th></tr><tr v-for="stock in state.stocks" :key="stock.symbol"><td>{{ stock.symbol }}</td><td>{{ stock.name }}</td><td>{{ stock.latestPrice }}</td><td>{{ stock.changePercent }}%</td></tr></table><h2>限价下单</h2><select v-model="side"><option>BUY</option><option>SELL</option></select><select v-model="symbol"><option v-for="stock in state.stocks" :value="stock.symbol">{{ stock.symbol }}</option></select><input v-model="price" type="number"><input v-model="quantity" type="number"><button @click="submit">提交</button><h2>未成交 / 部分成交</h2><ul><li v-for="order in openOrders" :key="order.id">{{ order.side }} {{ order.symbol }} {{ order.price }} 剩余 {{ order.remainingQuantity }}/{{ order.quantity }}（{{ order.status }}）</li></ul><h2>已成交</h2><ul><li v-for="order in filledOrders" :key="order.id">{{ order.side }} {{ order.symbol }} {{ order.price }} × {{ order.quantity }}（FILLED）</li></ul><h2>持仓</h2><ul><li v-for="(value, key) in state.positions" :key="key">{{ key }}：{{ value }}</li></ul><h2>最近成交</h2><ul><li v-for="trade in state.recentTrades" :key="trade.tradeId">{{ trade.symbol }} {{ trade.price }} × {{ trade.quantity }}</li></ul></section><p>{{ message }}</p></main></template>
<style>main{max-width:900px;margin:2rem auto;font:16px system-ui}input,select,button{margin:.25rem;padding:.45rem}table{border-collapse:collapse;width:100%}td,th{border:1px solid #ddd;padding:.5rem;text-align:left}</style>
